# Generated by Django 2.2 on 2020-09-06 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stemming', '0002_auto_20200906_0733'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Instagram_comment',
        ),
    ]
