# Generated by Django 2.2 on 2020-10-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stemming', '0003_auto_20200906_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stemming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.CharField(max_length=50)),
                ('stem', models.CharField(max_length=50)),
            ],
        ),
    ]
