# Generated by Django 2.2 on 2020-10-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stemming', '0004_stemming'),
    ]

    operations = [
        migrations.AddField(
            model_name='stemming',
            name='frek',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
